# Generated by Django 4.2.3 on 2023-07-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apepat', models.CharField(max_length=15)),
                ('apemat', models.CharField(max_length=15)),
                ('matric', models.CharField(max_length=6)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Empleadores',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
