# Generated by Django 4.2.3 on 2023-07-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0002_egresados_rename_articulos_empleadores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egresados',
            new_name='Egresado',
        ),
        migrations.RenameModel(
            old_name='Empleadores',
            new_name='Empleador',
        ),
    ]
