# Generated by Django 4.2.3 on 2023-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0003_rename_egresados_egresado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
