# Generated by Django 4.2.3 on 2023-07-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0004_alter_egresado_email_alter_empleador_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresado',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='empleador',
            old_name='number',
            new_name='numero',
        ),
    ]
