# Generated by Django 4.2.3 on 2023-07-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0005_rename_number_egresado_numero_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleador',
            new_name='Empleadore',
        ),
    ]
