# Generated by Django 4.2.3 on 2023-07-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0006_rename_empleador_empleadore'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='carrera',
            field=models.CharField(choices=[('Ing. Agroindustrial', 'Ing. de Software'), ('Ing. Animación y Efectos visuales', 'Ing. en Energia'), ('Ing. en Logistica y transporte', 'Ing. en Nanotecnologia'), ('Ing. Sistemas automotices', 'Ing. Tecnologia ambiental'), ('Ing. Financiera', 'Ing. Mecatronica')], default='Ing. Agroindustrial', max_length=50),
        ),
    ]
