# Generated by Django 4.2.3 on 2023-07-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0007_egresado_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='carrera',
            field=models.CharField(choices=[('Ing. Agroindustrial', ' '), ('Ing. de Software', ' '), ('Ing. Animación y Efectos visuales', ' '), ('Ing. en Energia', ' '), ('Ing. en Logistica y transporte', ' '), ('Ing. en Nanotecnologia', ' '), ('Ing. Sistemas automotices', ' '), ('Ing. Tecnologia ambiental', ' '), ('Ing. Financiera', ' '), ('Ing. Mecatronica', ' ')], default='Ing. Agroindustrial', max_length=50),
        ),
    ]
